name: Run Tests in Docker Container

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . -t app:latest

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v $PWD:/app \
            app \
            php artisan test
